# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-12 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buy_transaction',
            fields=[
                ('b_tid', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('impact', models.FloatField()),
                ('buyrate', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('balance', models.FloatField(default='0')),
                ('phonenumber', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='historical_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('highest_p', models.FloatField()),
                ('lowest_p', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='sell_transaction',
            fields=[
                ('s_tid', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('impact', models.FloatField()),
                ('sellrate', models.FloatField(null=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.customer')),
            ],
        ),
        migrations.CreateModel(
            name='shares',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('google_id', models.IntegerField()),
                ('stock_code', models.CharField(default='', max_length=50)),
                ('stock_name', models.CharField(max_length=100)),
                ('ceo_name', models.CharField(default='', max_length=100)),
                ('comp_desc', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='sell_transaction',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.shares'),
        ),
        migrations.AddField(
            model_name='historical_data',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.shares'),
        ),
        migrations.AddField(
            model_name='buy_transaction',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.customer'),
        ),
        migrations.AddField(
            model_name='buy_transaction',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.shares'),
        ),
    ]
