# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-20 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('balance', models.FloatField(default='0')),
                ('phonenumber', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='historical_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('highest_p', models.FloatField()),
                ('lowest_p', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='shares',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('stock_name', models.CharField(max_length=50)),
                ('stock_branch', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('impact', models.FloatField()),
                ('buyrate', models.FloatField(null=True)),
                ('sellrate', models.FloatField(null=True)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.Customer')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.shares')),
            ],
        ),
        migrations.AddField(
            model_name='historical_data',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.shares'),
        ),
    ]
