# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-14 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='two_step_validation',
            field=models.BooleanField(default=True),
        ),
    ]
