# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-21 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phonenumber',
            field=models.BigIntegerField(),
        ),
    ]
