# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-21 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_customer_two_step_validation'),
    ]

    operations = [
        migrations.CreateModel(
            name='brokerage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField()),
                ('type', models.CharField(choices=[('BUY', 'Buy Transaction'), ('SELL', 'Sell Transaction')], max_length=4)),
                ('brokerage', models.FloatField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.customer')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.shares')),
            ],
        ),
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_qty', models.IntegerField()),
                ('sell_qty', models.IntegerField()),
                ('amount', models.FloatField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.customer')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.shares')),
            ],
        ),
    ]
