# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-23 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_auto_20170821_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shares',
            name='stock_branch',
        ),
    ]
