# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-23 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_remove_shares_stock_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='shares',
            name='stock_code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
