# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-23 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0005_shares_stock_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shares',
            name='stock_name',
            field=models.CharField(max_length=100),
        ),
    ]
