# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0006_auto_20170823_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='shares',
            name='ceo_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shares',
            name='comp_desc',
            field=models.TextField(default=''),
        ),
    ]
