# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-01 04:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0007_auto_20170831_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='buy_transaction',
            fields=[
                ('b_tid', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('impact', models.FloatField()),
                ('buyrate', models.FloatField(null=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.customer')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.shares')),
            ],
        ),
        migrations.CreateModel(
            name='sell_transaction',
            fields=[
                ('s_tid', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('impact', models.FloatField()),
                ('sellrate', models.FloatField(null=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.customer')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.shares')),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sid',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
